--- #YAML:1.0
name:                CORBA-Python
version:             2.62
abstract:            IDL compiler to Python mapping
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36_02
distribution_type:   module
requires:     
    CORBA::C:                      2.6
    CORBA::IDL:                    2.6
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Francois PERRAD (francois.perrad@gadz.org)
